import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "MQTT-to-Firebase bridge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
